### PR TITLE
Tracker Feed Marquee

### PR DESCRIPTION
**Pull request by MichaelRoberts214**
Displays fictitious tracker alerts across the bottom of the dashboard

Below is a screenshot showing the feed as a part of the bottom footer.
screen shot 2015-11-18 at 9 56 52 pm

### CODE REVIEW

**Comment by lizkhoo** [comment]
Can you put the scrolling action and alerts message into the blue bar at
the bottom of the screen? That's what I meant by "news ticker" or "stock
ticker". Sorry if you received conflicting instruction from Matt.

**Comment by MichaelRoberts214** [comment]
No problem. Do you want all the text scrolling or have the scrolling text
in the bar above/below the static text?

**Comment by MichaelRoberts214** [comment]
@lizkhoo I went ahead and made the change to the scrolling feed. The screenshot above has been updated to show this.

**Comment by lizkhoo** [comment]
make the weather and alert info all inline (one line). sorry I didn't see your comment on this - you can make the change tomorrow afternoon if you don't have time before the Jabil call at 11am

**Comment by MichaelRoberts214** [comment]
@lizkhoo The change has been made - it was simple. The screenshot above has been updated as well.

**Pull request merged**
